language: node_js

sudo: false

node_js:
  - "node"

addons:
  apt:
    packages:
      - p7zip-full

env:
  global:
    - BASE_NAME=donation-encourager-$TRAVIS_TAG

cache:
  directories:
    - node_modules

script:
  - npm run test

before_deploy:
  - npm run prepare
  - npm run build_zip
